name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '6.0.x'

      - name: Show .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Test application
        run: dotnet test
